# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1
jobs:
  build:

    macos:
      xcode: "10.2.1"
    filters:
      # Both of the following conditions must be included!
      # Ignore any commit on any branch by default.
      # branches:
      #   only: master
      # Only act on version tags.
      # tags:
      #   only: /v[0-9]+(\.[0-9]+)*(\-rc(\.[0-9]+)?)?/

    steps:
      - checkout
      - run:
          name: Setup local environment
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm" >> $BASH_ENV
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            source $BASH_ENV
            nvm install node --lts
            git config --global user.email "turnrye@users.noreply.github.com"
            git config --global user.name "turnrye Deployment Script"
            echo "machine github.com login turnrye password $GITHUB_TOKEN" > ~/.netrc
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run the new release
          command: ./new-release.sh 0.60.4